# Generated by Django 5.0.4 on 2024-06-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hide_email",
        ),
        migrations.AddField(
            model_name="employer",
            name="hide_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="talent",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="talent",
            name="hide_email",
            field=models.BooleanField(default=True),
        ),
    ]
