# Generated by Django 5.0.4 on 2024-06-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_hide_email_employer_hide_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employer",
            name="hide_email",
        ),
        migrations.RemoveField(
            model_name="talent",
            name="email",
        ),
        migrations.RemoveField(
            model_name="talent",
            name="hide_email",
        ),
    ]
