# Generated by Django 5.0.4 on 2024-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_employer_hide_email_remove_talent_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="about",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employer",
            name="city",
            field=models.CharField(blank=True, default="", max_length=75),
        ),
        migrations.AlterField(
            model_name="employer",
            name="company",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="employer",
            name="country",
            field=models.CharField(blank=True, default="", max_length=56),
        ),
        migrations.AlterField(
            model_name="employer",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="employer",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="employer",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="employer",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="employer",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="talent",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="talent",
            name="city",
            field=models.CharField(blank=True, default="", max_length=75),
        ),
        migrations.AlterField(
            model_name="talent",
            name="country",
            field=models.CharField(blank=True, default="", max_length=56),
        ),
        migrations.AlterField(
            model_name="talent",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="talent",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="talent",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="talent",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="talent",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
