# Generated by Django 5.0.4 on 2024-06-28 15:23

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_employer_about_alter_employer_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talent",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/talent/resumes/",
                validators=[apps.user.models.validate_resume_extension],
            ),
        ),
    ]
