# Generated by Django 5.0.4 on 2024-06-28 18:38

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_talent_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="employer/profile/"
            ),
        ),
        migrations.AlterField(
            model_name="talent",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="talent/profile/"),
        ),
        migrations.AlterField(
            model_name="talent",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="talent/resumes/",
                validators=[apps.user.models.validate_resume_extension],
            ),
        ),
    ]
