# Generated by Django 5.0.4 on 2024-06-28 19:11

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_employer_image_alter_talent_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talent",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.user.models.talent_upload_profile_path,
            ),
        ),
        migrations.AlterField(
            model_name="talent",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.user.models.talent_upload_resume_path,
                validators=[apps.user.models.validate_resume_extension],
            ),
        ),
    ]
