# Generated by Django 5.0.4 on 2024-07-08 11:03

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_talent_image_alter_talent_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.user.models.employer_upload_profile_path,
            ),
        ),
    ]
