# Generated by Django 5.0.4 on 2024-06-08 12:40

import django.db.models.deletion
import django_jsonform.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=56, null=True)),
                ("country", models.CharField(blank=True, max_length=56, null=True)),
                ("salary", models.CharField(blank=True, max_length=40, null=True)),
                ("schedule", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "details",
                    django_jsonform.models.fields.JSONField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "job_listing",
            },
        ),
    ]
