# Generated by Django 5.0.4 on 2024-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.CharField(blank=True, default="", max_length=56),
        ),
        migrations.AlterField(
            model_name="job",
            name="country",
            field=models.CharField(blank=True, default="", max_length=56),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="job",
            name="schedule",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
